databases:
  - name: calendar_api
    databaseName: calendar_api
    user: calendar_api

services:
  - type: web
    name: calendar_api
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn calendar_api.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: calendar_api
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4